FROM openjdk:8u212-jre
MAINTAINER number47
COPY nebs-spring-gateway-1.0-SNAPSHOT.jar /nebs/nebs-spring-gateway-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/nebs/nebs-spring-gateway-1.0-SNAPSHOT.jar"]

