server:
  port: 8202

spring:
  application:
    name: NEBS-SERVER-TEST
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
                   com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration,
                   org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  boot:
    admin:
      client:
        url: http://${nebs-monitor-admin}:8401
        username: nebs
        password: 123456
  zipkin:
    sender:
      type: rabbit #指定了使用RabbitMQ收集追踪信息
  sleuth:
    sampler:
      probability: 1 #默认值为0.1，即采样率才1/10，发送10笔请求只有一笔会被采集。为了测试方便，我们可以将它设置为1，即100%采样；
  rabbitmq:
    host: ${rabbitmq.url}
    port: 5672  #5672是RabbitMQ的管理页面端口，5672是AMPQ端口
    username: nebs
    password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*' #将Spring Boot Admin客户端的所有监控端点都暴露给Spring Boot Admin服务端；
  endpoint:
    health:
      show-details: ALWAYS #总是展示详细的健康信息

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://nebs:123456@${nebs-register}:8001/register/eureka/
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://${nebs-gateway}:8301/auth/user
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true #把SecurityContext对象从你当前主线程传输到Hystrix线程
