version: '3'

services:
  nebs-monitor-admin:
    image: nebs-monitor-admin:latest
    container_name: nebs-monitor-admin
    volumes:
      - "/nebs/log:/log"
    command:
      - "--nacos.url=192.168.33.10"
      - "--nebs-monitor-admin=192.168.33.10"
    ports:
      - 8401:8401
  nebs-spring-gateway:
    image: nebs-spring-gateway:latest
    container_name: nebs-spring-gateway
    volumes:
      - "/nebs/log:/log"
    command:
      - "--mysql.url=192.168.33.10"
      - "--nacos.url=192.168.33.10"
      - "--redis.url=192.168.33.10"
      - "--nebs-register=192.168.33.10"
      - "--nebs-monitor-admin=192.168.33.10"
    ports:
      - 8301:8301
  nebs-auth:
    image: nebs-auth:latest
    container_name: nebs-auth
    volumes:
      - "/nebs/log:/log"
    command:
      - "--mysql.url=192.168.33.10"
      - "--nacos.url=192.168.33.10"
      - "--redis.url=192.168.33.10"
      - "--nebs-register=192.168.33.10"
      - "--nebs-monitor-admin=192.168.33.10"
    ports:
      - 8101:8101
  nebs-server-system:
    image: nebs-server-system:latest
    container_name: nebs-server-system
    volumes:
      - "/nebs/log:/log"
    command:
      - "--mysql.url=192.168.33.10"
      - "--nacos.url=192.168.33.10"
      - "--rabbitmq.url=192.168.33.10"
      - "--nebs-register=192.168.33.10"
      - "--nebs-monitor-admin=192.168.33.10"
      - "--nebs-gateway=192.168.33.10"
      - "--nebs-server-system=192.168.33.10"
      - "--nebs-gateway=192.168.33.10"
    ports:
      - 8201:8201
  nebs-server-test:
    image: nebs-server-test:latest
    container_name: nebs-server-test
    volumes:
      - "/nebs/log:/log"
    command:
      - "--nacos.url=192.168.33.10"
      - "--rabbitmq.url=192.168.33.10"
      - "--nebs-register=192.168.33.10"
      - "--nebs-monitor-admin=192.168.33.10"
      - "--nebs-gateway=192.168.33.10"
    ports:
      - 8202:8202
  zipkin-server:
    image: zipkin-server
    container_name: zipkin-server
    command:
      - "--server.port=8402"
      - "--zipkin.storage.type=mysql"
      - "--zipkin.storage.mysql.db=nebs_cloud_base"
      - "--zipkin.storage.mysql.username=root"
      - "--zipkin.storage.mysql.password=123456"
      - "--zipkin.storage.mysql.host=192.168.33.10"
      - "--zipkin.storage.mysql.port=3306"
      - "--zipkin.collector.rabbitmq.addresses=192.168.33.10:5672"
      - "--zipkin.collector.rabbitmq.username=nebs"
      - "--zipkin.collector.rabbitmq.password=123456"
    ports:
      - 8402:8402
