FROM openjdk:8u212-jre
MAINTAINER number47
COPY nebs-monitor-admin-1.0-SNAPSHOT.jar /nebs/nebs-monitor-admin-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/nebs/nebs-monitor-admin-1.0-SNAPSHOT.jar"]

